<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="2" failures="0" skipped="0" tests="2" time="1.469" timestamp="2021-12-02T17:18:00.513236" hostname="DESKTOP-F5PJJI8"><testcase classname="ui_tests.ui_test" name="test_search_xss" time="0.484"><error message="failed on setup with &quot;ValueError: response body:&#10;{'message': &quot;API rate limit exceeded for 118.189.138.35. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)&quot;, 'documentation_url': 'https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting'}&#10;request url:&#10;https://api.github.com/repos/mozilla/geckodriver/releases/latest&#10;response headers:&#10;{'Date': 'Thu, 02 Dec 2021 09:18:01 GMT', 'Server': 'Varnish', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains; preload', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'deny', 'X-XSS-Protection': '1; mode=block', 'Content-Security-Policy': &quot;default-src 'none'; style-src 'unsafe-inline'&quot;, 'Access-Control-Allow-Origin': '*', 'Access-Control-Expose-Headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-RateLimit-Used, X-RateLimit-Resource, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset', 'Content-Type': 'application/json; charset=utf-8', 'Referrer-Policy': 'origin-when-cross-origin, strict-origin-when-cross-origin', 'X-GitHub-Media-Type': 'github.v3; format=json', 'X-RateLimit-Limit': '60', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1638436904', 'X-RateLimit-Resource': 'core', 'X-RateLimit-Used': '60', 'Content-Length': '280', 'X-GitHub-Request-Id': '12DB:5170:EB54A:1111DC:61A88F49'}&quot;">@pytest.fixture()
    def test_setup():
    	global driver
    	options = Options()
    	options.headless = True
    
&gt;   	s = Firefox_Service(GeckoDriverManager().install())

ui_tests\ui_test.py:30: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
..\..\..\envs\ssd_test\lib\site-packages\webdriver_manager\firefox.py:29: in install
    return self._get_driver_path(self.driver)
..\..\..\envs\ssd_test\lib\site-packages\webdriver_manager\manager.py:23: in _get_driver_path
    driver_version = driver.get_version()
..\..\..\envs\ssd_test\lib\site-packages\webdriver_manager\driver.py:41: in get_version
    return self.get_latest_release_version()
..\..\..\envs\ssd_test\lib\site-packages\webdriver_manager\driver.py:115: in get_latest_release_version
    validate_response(resp)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

resp = &lt;Response [403]&gt;

    def validate_response(resp):
        if resp.status_code == 404:
            raise ValueError("There is no such driver by url {}".format(resp.url))
        elif resp.status_code != 200:
&gt;           raise ValueError(
                f'response body:\n{resp.json()}\n'
                f'request url:\n{resp.request.url}\n'
                f'response headers:\n{dict(resp.headers)}\n'
            )
E           ValueError: response body:
E           {'message': "API rate limit exceeded for 118.189.138.35. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)", 'documentation_url': 'https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting'}
E           request url:
E           https://api.github.com/repos/mozilla/geckodriver/releases/latest
E           response headers:
E           {'Date': 'Thu, 02 Dec 2021 09:18:01 GMT', 'Server': 'Varnish', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains; preload', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'deny', 'X-XSS-Protection': '1; mode=block', 'Content-Security-Policy': "default-src 'none'; style-src 'unsafe-inline'", 'Access-Control-Allow-Origin': '*', 'Access-Control-Expose-Headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-RateLimit-Used, X-RateLimit-Resource, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset', 'Content-Type': 'application/json; charset=utf-8', 'Referrer-Policy': 'origin-when-cross-origin, strict-origin-when-cross-origin', 'X-GitHub-Media-Type': 'github.v3; format=json', 'X-RateLimit-Limit': '60', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1638436904', 'X-RateLimit-Resource': 'core', 'X-RateLimit-Used': '60', 'Content-Length': '280', 'X-GitHub-Request-Id': '12DB:5170:EB54A:1111DC:61A88F49'}

..\..\..\envs\ssd_test\lib\site-packages\webdriver_manager\utils.py:82: ValueError</error></testcase><testcase classname="ui_tests.ui_test" name="test_no_xss" time="0.410"><error message="failed on setup with &quot;ValueError: response body:&#10;{'message': &quot;API rate limit exceeded for 118.189.138.35. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)&quot;, 'documentation_url': 'https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting'}&#10;request url:&#10;https://api.github.com/repos/mozilla/geckodriver/releases/latest&#10;response headers:&#10;{'Date': 'Thu, 02 Dec 2021 09:18:01 GMT', 'Server': 'Varnish', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains; preload', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'deny', 'X-XSS-Protection': '1; mode=block', 'Content-Security-Policy': &quot;default-src 'none'; style-src 'unsafe-inline'&quot;, 'Access-Control-Allow-Origin': '*', 'Access-Control-Expose-Headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-RateLimit-Used, X-RateLimit-Resource, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset', 'Content-Type': 'application/json; charset=utf-8', 'Referrer-Policy': 'origin-when-cross-origin, strict-origin-when-cross-origin', 'X-GitHub-Media-Type': 'github.v3; format=json', 'X-RateLimit-Limit': '60', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1638436904', 'X-RateLimit-Resource': 'core', 'X-RateLimit-Used': '60', 'Content-Length': '280', 'X-GitHub-Request-Id': 'DBAB:13E7:570C6:7C10B:61A88F49'}&quot;">@pytest.fixture()
    def test_setup():
    	global driver
    	options = Options()
    	options.headless = True
    
&gt;   	s = Firefox_Service(GeckoDriverManager().install())

ui_tests\ui_test.py:30: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
..\..\..\envs\ssd_test\lib\site-packages\webdriver_manager\firefox.py:29: in install
    return self._get_driver_path(self.driver)
..\..\..\envs\ssd_test\lib\site-packages\webdriver_manager\manager.py:23: in _get_driver_path
    driver_version = driver.get_version()
..\..\..\envs\ssd_test\lib\site-packages\webdriver_manager\driver.py:41: in get_version
    return self.get_latest_release_version()
..\..\..\envs\ssd_test\lib\site-packages\webdriver_manager\driver.py:115: in get_latest_release_version
    validate_response(resp)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

resp = &lt;Response [403]&gt;

    def validate_response(resp):
        if resp.status_code == 404:
            raise ValueError("There is no such driver by url {}".format(resp.url))
        elif resp.status_code != 200:
&gt;           raise ValueError(
                f'response body:\n{resp.json()}\n'
                f'request url:\n{resp.request.url}\n'
                f'response headers:\n{dict(resp.headers)}\n'
            )
E           ValueError: response body:
E           {'message': "API rate limit exceeded for 118.189.138.35. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)", 'documentation_url': 'https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting'}
E           request url:
E           https://api.github.com/repos/mozilla/geckodriver/releases/latest
E           response headers:
E           {'Date': 'Thu, 02 Dec 2021 09:18:01 GMT', 'Server': 'Varnish', 'Strict-Transport-Security': 'max-age=31536000; includeSubdomains; preload', 'X-Content-Type-Options': 'nosniff', 'X-Frame-Options': 'deny', 'X-XSS-Protection': '1; mode=block', 'Content-Security-Policy': "default-src 'none'; style-src 'unsafe-inline'", 'Access-Control-Allow-Origin': '*', 'Access-Control-Expose-Headers': 'ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-RateLimit-Used, X-RateLimit-Resource, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, Deprecation, Sunset', 'Content-Type': 'application/json; charset=utf-8', 'Referrer-Policy': 'origin-when-cross-origin, strict-origin-when-cross-origin', 'X-GitHub-Media-Type': 'github.v3; format=json', 'X-RateLimit-Limit': '60', 'X-RateLimit-Remaining': '0', 'X-RateLimit-Reset': '1638436904', 'X-RateLimit-Resource': 'core', 'X-RateLimit-Used': '60', 'Content-Length': '280', 'X-GitHub-Request-Id': 'DBAB:13E7:570C6:7C10B:61A88F49'}

..\..\..\envs\ssd_test\lib\site-packages\webdriver_manager\utils.py:82: ValueError</error></testcase></testsuite></testsuites>